# Generated by Django 4.0.6 on 2022-08-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
