# Generated by Django 4.1.3 on 2022-12-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_grade_delete_schoolhistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
